/*
 * Generated by JasperReports - 4/8/07 5:16 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import java.util.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class estado_de_cuenta_1176067009338_395936 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_p_id_solicitud = null;
    private JRFillParameter parameter_REPORT_DATE_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_SUBREPORT_DIR = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillField field_monto_mora = null;
    private JRFillField field_id_solicitud = null;
    private JRFillField field_id_prestamo = null;
    private JRFillField field_fecha_inicio = null;
    private JRFillField field_numero_acta_directorio = null;
    private JRFillField field_base_calculo_intereses = null;
    private JRFillField field_dia_facturacion = null;
    private JRFillField field_meses_fijos_sin_cambio_tasa = null;
    private JRFillField field_id_partida = null;
    private JRFillField field_deuda = null;
    private JRFillField field_interes_diferido_vencido = null;
    private JRFillField field_interes_desembolso_vencido = null;
    private JRFillField field_nombre_empresa = null;
    private JRFillField field_tasa_vigente = null;
    private JRFillField field_numero_prestamo = null;
    private JRFillField field_nombre_programa = null;
    private JRFillField field_exigible = null;
    private JRFillField field_frecuencia_pago = null;
    private JRFillField field_id_empresa = null;
    private JRFillField field_numero_resolucion_directorio = null;
    private JRFillField field_cantidad_cuotas_vencidas = null;
    private JRFillField field_remanente_por_aplicar = null;
    private JRFillField field_numero_solicitud = null;
    private JRFillField field_estatus = null;
    private JRFillField field_cp = null;
    private JRFillField field_id_programa = null;
    private JRFillField field_dias_mora = null;
    private JRFillField field_fecha_acta_directorio = null;
    private JRFillField field_saldo_insoluto = null;
    private JRFillField field_capital_vencido = null;
    private JRFillField field_interes_vencido = null;
    private JRFillField field_causado_no_devengado = null;
    private JRFillField field_prestamo_monto_solicitado = null;
    private JRFillField field_rif = null;
    private JRFillField field_tasa_fija = null;
    private JRFillField field_monto_solicitado = null;
    private JRFillField field_nombre_tipo_credito = null;
    private JRFillField field_nombre_partida = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_solicitud_COUNT = null;
    private JRFillVariable variable_prestamo_COUNT = null;
    private JRFillVariable variable_v_estatus = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_p_id_solicitud = (JRFillParameter)pm.get("p_id_solicitud");
        parameter_REPORT_DATE_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_DATE_FORMAT_FACTORY");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_SUBREPORT_DIR = (JRFillParameter)pm.get("SUBREPORT_DIR");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_monto_mora = (JRFillField)fm.get("monto_mora");
        field_id_solicitud = (JRFillField)fm.get("id_solicitud");
        field_id_prestamo = (JRFillField)fm.get("id_prestamo");
        field_fecha_inicio = (JRFillField)fm.get("fecha_inicio");
        field_numero_acta_directorio = (JRFillField)fm.get("numero_acta_directorio");
        field_base_calculo_intereses = (JRFillField)fm.get("base_calculo_intereses");
        field_dia_facturacion = (JRFillField)fm.get("dia_facturacion");
        field_meses_fijos_sin_cambio_tasa = (JRFillField)fm.get("meses_fijos_sin_cambio_tasa");
        field_id_partida = (JRFillField)fm.get("id_partida");
        field_deuda = (JRFillField)fm.get("deuda");
        field_interes_diferido_vencido = (JRFillField)fm.get("interes_diferido_vencido");
        field_interes_desembolso_vencido = (JRFillField)fm.get("interes_desembolso_vencido");
        field_nombre_empresa = (JRFillField)fm.get("nombre_empresa");
        field_tasa_vigente = (JRFillField)fm.get("tasa_vigente");
        field_numero_prestamo = (JRFillField)fm.get("numero_prestamo");
        field_nombre_programa = (JRFillField)fm.get("nombre_programa");
        field_exigible = (JRFillField)fm.get("exigible");
        field_frecuencia_pago = (JRFillField)fm.get("frecuencia_pago");
        field_id_empresa = (JRFillField)fm.get("id_empresa");
        field_numero_resolucion_directorio = (JRFillField)fm.get("numero_resolucion_directorio");
        field_cantidad_cuotas_vencidas = (JRFillField)fm.get("cantidad_cuotas_vencidas");
        field_remanente_por_aplicar = (JRFillField)fm.get("remanente_por_aplicar");
        field_numero_solicitud = (JRFillField)fm.get("numero_solicitud");
        field_estatus = (JRFillField)fm.get("estatus");
        field_cp = (JRFillField)fm.get("cp");
        field_id_programa = (JRFillField)fm.get("id_programa");
        field_dias_mora = (JRFillField)fm.get("dias_mora");
        field_fecha_acta_directorio = (JRFillField)fm.get("fecha_acta_directorio");
        field_saldo_insoluto = (JRFillField)fm.get("saldo_insoluto");
        field_capital_vencido = (JRFillField)fm.get("capital_vencido");
        field_interes_vencido = (JRFillField)fm.get("interes_vencido");
        field_causado_no_devengado = (JRFillField)fm.get("causado_no_devengado");
        field_prestamo_monto_solicitado = (JRFillField)fm.get("prestamo_monto_solicitado");
        field_rif = (JRFillField)fm.get("rif");
        field_tasa_fija = (JRFillField)fm.get("tasa_fija");
        field_monto_solicitado = (JRFillField)fm.get("monto_solicitado");
        field_nombre_tipo_credito = (JRFillField)fm.get("nombre_tipo_credito");
        field_nombre_partida = (JRFillField)fm.get("nombre_partida");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_solicitud_COUNT = (JRFillVariable)vm.get("solicitud_COUNT");
        variable_prestamo_COUNT = (JRFillVariable)vm.get("prestamo_COUNT");
        variable_v_estatus = (JRFillVariable)vm.get("v_estatus");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("./");
                break;
            }
            case 1 : 
            {
                value = (java.lang.Long)(new Long(1));
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 14 : 
            {
                value = (java.lang.String)(((java.lang.String)field_estatus.getValue()).equals ("P")?"Vigente":
((java.lang.String)field_estatus.getValue()).equals ("V")?"Vigente":
((java.lang.String)field_estatus.getValue()).equals ("E")?"Vencido":
((java.lang.String)field_estatus.getValue()).equals ("C")?"Cancelado":" ");
                break;
            }
            case 15 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_solicitud.getValue()));
                break;
            }
            case 16 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_solicitud.getValue()).toString() + ((java.lang.Integer)field_id_prestamo.getValue()));
                break;
            }
            case 17 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_prestamo.getValue()));
                break;
            }
            case 18 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "sub_plan_amortizacion_intermediario.jasper");
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_partida.getValue()));
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.Boolean)field_tasa_fija.getValue()).equals("True") ? "Tasa Fija" : "Variable");
                break;
            }
            case 22 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_tasa_vigente.getValue()));
                break;
            }
            case 23 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_numero_prestamo.getValue()));
                break;
            }
            case 24 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_prestamo_monto_solicitado.getValue()));
                break;
            }
            case 25 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_meses_fijos_sin_cambio_tasa.getValue()));
                break;
            }
            case 26 : 
            {
                value = (java.util.Date)(((java.sql.Date)field_fecha_inicio.getValue()));
                break;
            }
            case 27 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_base_calculo_intereses.getValue()));
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_tipo_credito.getValue()));
                break;
            }
            case 29 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_dia_facturacion.getValue()));
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)field_estatus.getValue()).equals ("P")?"Vigente":
((java.lang.String)field_estatus.getValue()).equals ("V")?"Vigente":
((java.lang.String)field_estatus.getValue()).equals ("E")?"Vencido":
((java.lang.String)field_estatus.getValue()).equals ("C")?"Cancelado":" ");
                break;
            }
            case 31 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_cantidad_cuotas_vencidas.getValue()));
                break;
            }
            case 32 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_dias_mora.getValue()));
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_saldo_insoluto.getValue()));
                break;
            }
            case 34 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_interes_diferido_vencido.getValue()));
                break;
            }
            case 35 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_interes_diferido_vencido.getValue()));
                break;
            }
            case 36 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_interes_desembolso_vencido.getValue()));
                break;
            }
            case 37 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_monto_mora.getValue()));
                break;
            }
            case 38 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_monto_mora.getValue()));
                break;
            }
            case 39 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_interes_vencido.getValue()));
                break;
            }
            case 40 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_interes_vencido.getValue()));
                break;
            }
            case 41 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_causado_no_devengado.getValue()));
                break;
            }
            case 42 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_remanente_por_aplicar.getValue()));
                break;
            }
            case 43 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_remanente_por_aplicar.getValue()));
                break;
            }
            case 44 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_deuda.getValue()));
                break;
            }
            case 45 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_capital_vencido.getValue()));
                break;
            }
            case 46 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_exigible.getValue()));
                break;
            }
            case 47 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_cantidad_cuotas_vencidas.getValue()));
                break;
            }
            case 48 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_cp.getValue()));
                break;
            }
            case 49 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_prestamo.getValue()));
                break;
            }
            case 50 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "sub_historico.jasper");
                break;
            }
            case 52 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_prestamo.getValue()));
                break;
            }
            case 53 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 54 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "sub_ultimo_pago.jasper");
                break;
            }
            case 55 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_prestamo.getValue()));
                break;
            }
            case 56 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 57 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "sub_ultimo_abono_extraordinario.jasper");
                break;
            }
            case 58 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_prestamo.getValue()));
                break;
            }
            case 59 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 60 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "sub_ultimo_desembolso.jasper");
                break;
            }
            case 61 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_numero_solicitud.getValue()));
                break;
            }
            case 62 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_programa.getValue()));
                break;
            }
            case 63 : 
            {
                value = (java.lang.String)(((java.lang.String)field_numero_acta_directorio.getValue()));
                break;
            }
            case 64 : 
            {
                value = (java.lang.String)(((java.lang.String)field_numero_resolucion_directorio.getValue()));
                break;
            }
            case 65 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_monto_solicitado.getValue()));
                break;
            }
            case 66 : 
            {
                value = (java.util.Date)(((java.sql.Date)field_fecha_acta_directorio.getValue()));
                break;
            }
            case 67 : 
            {
                value = (java.lang.String)("./logo_foncrei.jpg");
                break;
            }
            case 68 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_empresa.getValue()));
                break;
            }
            case 69 : 
            {
                value = (java.lang.String)(((java.lang.String)field_rif.getValue()));
                break;
            }
            case 70 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_empresa.getValue()));
                break;
            }
            case 71 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 72 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "sub_direccion.jasper");
                break;
            }
            case 73 : 
            {
                value = (java.lang.String)("Pag. " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 74 : 
            {
                value = (java.lang.String)(" / " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 75 : 
            {
                value = (java.util.Date)(new Date());
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("./");
                break;
            }
            case 1 : 
            {
                value = (java.lang.Long)(new Long(1));
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 14 : 
            {
                value = (java.lang.String)(((java.lang.String)field_estatus.getOldValue()).equals ("P")?"Vigente":
((java.lang.String)field_estatus.getOldValue()).equals ("V")?"Vigente":
((java.lang.String)field_estatus.getOldValue()).equals ("E")?"Vencido":
((java.lang.String)field_estatus.getOldValue()).equals ("C")?"Cancelado":" ");
                break;
            }
            case 15 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_solicitud.getOldValue()));
                break;
            }
            case 16 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_solicitud.getOldValue()).toString() + ((java.lang.Integer)field_id_prestamo.getOldValue()));
                break;
            }
            case 17 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_prestamo.getOldValue()));
                break;
            }
            case 18 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "sub_plan_amortizacion_intermediario.jasper");
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_partida.getOldValue()));
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.Boolean)field_tasa_fija.getOldValue()).equals("True") ? "Tasa Fija" : "Variable");
                break;
            }
            case 22 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_tasa_vigente.getOldValue()));
                break;
            }
            case 23 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_numero_prestamo.getOldValue()));
                break;
            }
            case 24 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_prestamo_monto_solicitado.getOldValue()));
                break;
            }
            case 25 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_meses_fijos_sin_cambio_tasa.getOldValue()));
                break;
            }
            case 26 : 
            {
                value = (java.util.Date)(((java.sql.Date)field_fecha_inicio.getOldValue()));
                break;
            }
            case 27 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_base_calculo_intereses.getOldValue()));
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_tipo_credito.getOldValue()));
                break;
            }
            case 29 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_dia_facturacion.getOldValue()));
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)field_estatus.getOldValue()).equals ("P")?"Vigente":
((java.lang.String)field_estatus.getOldValue()).equals ("V")?"Vigente":
((java.lang.String)field_estatus.getOldValue()).equals ("E")?"Vencido":
((java.lang.String)field_estatus.getOldValue()).equals ("C")?"Cancelado":" ");
                break;
            }
            case 31 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_cantidad_cuotas_vencidas.getOldValue()));
                break;
            }
            case 32 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_dias_mora.getOldValue()));
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_saldo_insoluto.getOldValue()));
                break;
            }
            case 34 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_interes_diferido_vencido.getOldValue()));
                break;
            }
            case 35 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_interes_diferido_vencido.getOldValue()));
                break;
            }
            case 36 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_interes_desembolso_vencido.getOldValue()));
                break;
            }
            case 37 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_monto_mora.getOldValue()));
                break;
            }
            case 38 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_monto_mora.getOldValue()));
                break;
            }
            case 39 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_interes_vencido.getOldValue()));
                break;
            }
            case 40 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_interes_vencido.getOldValue()));
                break;
            }
            case 41 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_causado_no_devengado.getOldValue()));
                break;
            }
            case 42 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_remanente_por_aplicar.getOldValue()));
                break;
            }
            case 43 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_remanente_por_aplicar.getOldValue()));
                break;
            }
            case 44 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_deuda.getOldValue()));
                break;
            }
            case 45 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_capital_vencido.getOldValue()));
                break;
            }
            case 46 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_exigible.getOldValue()));
                break;
            }
            case 47 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_cantidad_cuotas_vencidas.getOldValue()));
                break;
            }
            case 48 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_cp.getOldValue()));
                break;
            }
            case 49 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_prestamo.getOldValue()));
                break;
            }
            case 50 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "sub_historico.jasper");
                break;
            }
            case 52 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_prestamo.getOldValue()));
                break;
            }
            case 53 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 54 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "sub_ultimo_pago.jasper");
                break;
            }
            case 55 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_prestamo.getOldValue()));
                break;
            }
            case 56 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 57 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "sub_ultimo_abono_extraordinario.jasper");
                break;
            }
            case 58 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_prestamo.getOldValue()));
                break;
            }
            case 59 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 60 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "sub_ultimo_desembolso.jasper");
                break;
            }
            case 61 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_numero_solicitud.getOldValue()));
                break;
            }
            case 62 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_programa.getOldValue()));
                break;
            }
            case 63 : 
            {
                value = (java.lang.String)(((java.lang.String)field_numero_acta_directorio.getOldValue()));
                break;
            }
            case 64 : 
            {
                value = (java.lang.String)(((java.lang.String)field_numero_resolucion_directorio.getOldValue()));
                break;
            }
            case 65 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_monto_solicitado.getOldValue()));
                break;
            }
            case 66 : 
            {
                value = (java.util.Date)(((java.sql.Date)field_fecha_acta_directorio.getOldValue()));
                break;
            }
            case 67 : 
            {
                value = (java.lang.String)("./logo_foncrei.jpg");
                break;
            }
            case 68 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_empresa.getOldValue()));
                break;
            }
            case 69 : 
            {
                value = (java.lang.String)(((java.lang.String)field_rif.getOldValue()));
                break;
            }
            case 70 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_empresa.getOldValue()));
                break;
            }
            case 71 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 72 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "sub_direccion.jasper");
                break;
            }
            case 73 : 
            {
                value = (java.lang.String)("Pag. " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 74 : 
            {
                value = (java.lang.String)(" / " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 75 : 
            {
                value = (java.util.Date)(new Date());
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("./");
                break;
            }
            case 1 : 
            {
                value = (java.lang.Long)(new Long(1));
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 14 : 
            {
                value = (java.lang.String)(((java.lang.String)field_estatus.getValue()).equals ("P")?"Vigente":
((java.lang.String)field_estatus.getValue()).equals ("V")?"Vigente":
((java.lang.String)field_estatus.getValue()).equals ("E")?"Vencido":
((java.lang.String)field_estatus.getValue()).equals ("C")?"Cancelado":" ");
                break;
            }
            case 15 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_solicitud.getValue()));
                break;
            }
            case 16 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_solicitud.getValue()).toString() + ((java.lang.Integer)field_id_prestamo.getValue()));
                break;
            }
            case 17 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_prestamo.getValue()));
                break;
            }
            case 18 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "sub_plan_amortizacion_intermediario.jasper");
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_partida.getValue()));
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.Boolean)field_tasa_fija.getValue()).equals("True") ? "Tasa Fija" : "Variable");
                break;
            }
            case 22 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_tasa_vigente.getValue()));
                break;
            }
            case 23 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_numero_prestamo.getValue()));
                break;
            }
            case 24 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_prestamo_monto_solicitado.getValue()));
                break;
            }
            case 25 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_meses_fijos_sin_cambio_tasa.getValue()));
                break;
            }
            case 26 : 
            {
                value = (java.util.Date)(((java.sql.Date)field_fecha_inicio.getValue()));
                break;
            }
            case 27 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_base_calculo_intereses.getValue()));
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_tipo_credito.getValue()));
                break;
            }
            case 29 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_dia_facturacion.getValue()));
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)field_estatus.getValue()).equals ("P")?"Vigente":
((java.lang.String)field_estatus.getValue()).equals ("V")?"Vigente":
((java.lang.String)field_estatus.getValue()).equals ("E")?"Vencido":
((java.lang.String)field_estatus.getValue()).equals ("C")?"Cancelado":" ");
                break;
            }
            case 31 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_cantidad_cuotas_vencidas.getValue()));
                break;
            }
            case 32 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_dias_mora.getValue()));
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_saldo_insoluto.getValue()));
                break;
            }
            case 34 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_interes_diferido_vencido.getValue()));
                break;
            }
            case 35 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_interes_diferido_vencido.getValue()));
                break;
            }
            case 36 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_interes_desembolso_vencido.getValue()));
                break;
            }
            case 37 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_monto_mora.getValue()));
                break;
            }
            case 38 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_monto_mora.getValue()));
                break;
            }
            case 39 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_interes_vencido.getValue()));
                break;
            }
            case 40 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_interes_vencido.getValue()));
                break;
            }
            case 41 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_causado_no_devengado.getValue()));
                break;
            }
            case 42 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_remanente_por_aplicar.getValue()));
                break;
            }
            case 43 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_remanente_por_aplicar.getValue()));
                break;
            }
            case 44 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_deuda.getValue()));
                break;
            }
            case 45 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_capital_vencido.getValue()));
                break;
            }
            case 46 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_exigible.getValue()));
                break;
            }
            case 47 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_cantidad_cuotas_vencidas.getValue()));
                break;
            }
            case 48 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_cp.getValue()));
                break;
            }
            case 49 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_prestamo.getValue()));
                break;
            }
            case 50 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "sub_historico.jasper");
                break;
            }
            case 52 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_prestamo.getValue()));
                break;
            }
            case 53 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 54 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "sub_ultimo_pago.jasper");
                break;
            }
            case 55 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_prestamo.getValue()));
                break;
            }
            case 56 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 57 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "sub_ultimo_abono_extraordinario.jasper");
                break;
            }
            case 58 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_prestamo.getValue()));
                break;
            }
            case 59 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 60 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "sub_ultimo_desembolso.jasper");
                break;
            }
            case 61 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_numero_solicitud.getValue()));
                break;
            }
            case 62 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_programa.getValue()));
                break;
            }
            case 63 : 
            {
                value = (java.lang.String)(((java.lang.String)field_numero_acta_directorio.getValue()));
                break;
            }
            case 64 : 
            {
                value = (java.lang.String)(((java.lang.String)field_numero_resolucion_directorio.getValue()));
                break;
            }
            case 65 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_monto_solicitado.getValue()));
                break;
            }
            case 66 : 
            {
                value = (java.util.Date)(((java.sql.Date)field_fecha_acta_directorio.getValue()));
                break;
            }
            case 67 : 
            {
                value = (java.lang.String)("./logo_foncrei.jpg");
                break;
            }
            case 68 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_empresa.getValue()));
                break;
            }
            case 69 : 
            {
                value = (java.lang.String)(((java.lang.String)field_rif.getValue()));
                break;
            }
            case 70 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)field_id_empresa.getValue()));
                break;
            }
            case 71 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 72 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "sub_direccion.jasper");
                break;
            }
            case 73 : 
            {
                value = (java.lang.String)("Pag. " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 74 : 
            {
                value = (java.lang.String)(" / " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 75 : 
            {
                value = (java.util.Date)(new Date());
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
