delete from producto_formula where producto_id in (select id from producto where programa_id not in (1009, 1010, 1011));
delete from producto_rubro where producto_id in (select id from producto where programa_id not in (1009, 1010, 1011));
delete from producto_tipo_gasto where producto_id in (select id from producto where programa_id not in (1009, 1010, 1011));
delete from producto where programa_id not in (1009, 1010, 1011); 
delete from programa_modalidad_financiamiento where programa_id not in (1009, 1010, 1011);
delete from programa_origen_fondo where programa_id not in (1009, 1010, 1011);
delete from programa_recaudo where programa_id not in (1009, 1010, 1011);
delete from programa_tipo_garantia where programa_id not in (1009, 1010, 1011);
delete from acumulado_programa where programa_id not in (1009, 1010, 1011);
delete from meta_programa where programa_id not in (1009, 1010, 1011);
delete from programa where id not in (1009, 1010, 1011);
delete from meta_region;
delete from meta_sector_industrial;
delete from meta_tipo_credito;
delete from meta_tipo_empresa;
delete from meta where id in (select meta_id from meta_programa where programa_id not in (1009, 1010, 1011));
delete from acumulado_agrupacion_industrial;
delete from acumulado_entidad_financiera;
delete from acumulado_region;
delete from acumulado_tamano_empresa;
delete from acumulado_tipo_cliente;
delete from acumulado_tipo_credito;
delete from acumulado;
SELECT setval('empresa_id_seq', 1, true);
SELECT setval('empresa_integrante_id_seq', 1, true);
SELECT setval('empresa_integrante_tipo_id_seq', 1, true);
SELECT setval('empresa_telefono_id_seq', 1, true);
SELECT setval('empresa_direccion_id_seq', 1, true);
SELECT setval('empresa_email_id_seq', 1, true);
SELECT setval('programa_id_seq', 1, true);
SELECT setval('programa_origen_fondo_id_seq', 1, true);
SELECT setval('programa_tipo_garantia_id_seq', 1, true);
SELECT setval('acumulado_agrupacion_industrial_id_seq', 1, true);
SELECT setval('acumulado_entidad_financiera_id_seq', 1, true);
SELECT setval('acumulado_programa_id_seq', 1, true);
SELECT setval('acumulado_id_seq', 1, true);
SELECT setval('acumulado_region_id_seq', 1, true);
SELECT setval('acumulado_tamano_empresa_id_seq', 1, true);
SELECT setval('acumulado_tipo_cliente_id_seq', 1, true);
SELECT setval('acumulado_tipo_credito_id_seq', 1, true);
SELECT setval('meta_id_seq', 1, true);
SELECT setval('meta_programa_id_seq', 1, true);
SELECT setval('meta_region_id_seq', 1, true);
SELECT setval('meta_sector_industrial_id_seq', 1, true);
SELECT setval('meta_tipo_credito_id_seq', 1, true);
SELECT setval('meta_tipo_empresa_id_seq', 1, true);
SELECT setval('prestamo_id_seq', 1, true);
SELECT setval('prestamo_modificacion_id_seq', 1, true);
SELECT setval('prestamo_modificacion_rubro_atributo_id_seq', 1, true);
SELECT setval('prestamo_modificacion_rubro_id_seq', 1, true);
SELECT setval('prestamo_rubro_atributo_id_seq', 1, true);
SELECT setval('prestamo_rubro_id_seq', 1, true);
SELECT setval('prestamo_tasa_historico_id_seq', 1, true);
SELECT setval('solicitud_anticipo_societario_id_seq', 1, true);
SELECT setval('solicitud_capacidad_id_seq', 1, true);
SELECT setval('solicitud_evento_id_seq', 1, true);
SELECT setval('solicitud_historico_id_seq', 1, true);
SELECT setval('solicitud_id_seq', 1, true);
SELECT setval('solicitud_recaudo_id_seq', 1, true);
SELECT setval('cliente_antecedente_id_seq', 1, true);
SELECT setval('cliente_id_seq', 1, true);
SELECT setval('factura_id_seq', 1, true);
SELECT setval('pago_banco_comunal_id_seq', 1, true);
SELECT setval('pago_cliente_id_seq', 1, true);
SELECT setval('pago_cuota_id_seq', 1, true);
SELECT setval('pago_forma_id_seq', 1, true);
SELECT setval('pago_prestamo_id_seq', 1, true);
SELECT setval('desembolso_id_seq', 1, true);
SELECT setval('desembolso_pago_id_seq', 1, true);
SELECT setval('condicionamiento_desembolso_id_seq', 1, true);
SELECT setval('garantia_id_seq', 1, true);
SELECT setval('resultado_cualitativa_id_seq', 1, true);
SELECT setval('evaluacion_analisis_costos_id_seq', 1, true);
SELECT setval('evaluacion_cualitativa_id_seq', 1, true);
SELECT setval('evaluacion_financiera_id_seq', 1, true);
SELECT setval('evaluacion_flujo_caja_detalle_id_seq', 1, true);
SELECT setval('evaluacion_flujo_caja_id_seq', 1, true);
SELECT setval('evaluacion_id_seq', 1, true);
SELECT setval('evaluacion_plan_inversion_id_seq', 1, true);
SELECT setval('persona_direccion_id_seq', 1, true);
SELECT setval('persona_email_id_seq', 1, true);
SELECT setval('persona_id_seq', 1, true);
SELECT setval('persona_telefono_id_seq', 1, true);
