/*
 * Generated by JasperReports - 6/11/07 9:49 AM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import java.util.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class desembolso_mes_1181569769238_516303 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_p_anio_fin = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_p_dia_fin = null;
    private JRFillParameter parameter_REPORT_DATE_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_p_mes_inicio = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_p_mes_fin = null;
    private JRFillParameter parameter_p_anio_inicio = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_p_dia_inicio = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillField field_fecha_desembolso = null;
    private JRFillField field_empleos_directos = null;
    private JRFillField field_sector_economico = null;
    private JRFillField field_destino_del_credito = null;
    private JRFillField field_numero_hombres = null;
    private JRFillField field_tipo_de_organizacion = null;
    private JRFillField field_rif = null;
    private JRFillField field_tasa = null;
    private JRFillField field_empleos_indirectos = null;
    private JRFillField field_beneficiario = null;
    private JRFillField field_numero_mujeres = null;
    private JRFillField field_periodo_de_gracia = null;
    private JRFillField field_plazo = null;
    private JRFillField field_monto_liquidado = null;
    private JRFillField field_municipio = null;
    private JRFillField field_actividad_economica = null;
    private JRFillField field_estado = null;
    private JRFillField field_numero_acta_de_aprobacion = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_v_sum_total_monto_liquidado_by_report = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_p_anio_fin = (JRFillParameter)pm.get("p_anio_fin");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_p_dia_fin = (JRFillParameter)pm.get("p_dia_fin");
        parameter_REPORT_DATE_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_DATE_FORMAT_FACTORY");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_p_mes_inicio = (JRFillParameter)pm.get("p_mes_inicio");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_p_mes_fin = (JRFillParameter)pm.get("p_mes_fin");
        parameter_p_anio_inicio = (JRFillParameter)pm.get("p_anio_inicio");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_p_dia_inicio = (JRFillParameter)pm.get("p_dia_inicio");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_fecha_desembolso = (JRFillField)fm.get("fecha_desembolso");
        field_empleos_directos = (JRFillField)fm.get("empleos_directos");
        field_sector_economico = (JRFillField)fm.get("sector_economico");
        field_destino_del_credito = (JRFillField)fm.get("destino_del_credito");
        field_numero_hombres = (JRFillField)fm.get("numero_hombres");
        field_tipo_de_organizacion = (JRFillField)fm.get("tipo_de_organizacion");
        field_rif = (JRFillField)fm.get("rif");
        field_tasa = (JRFillField)fm.get("tasa");
        field_empleos_indirectos = (JRFillField)fm.get("empleos_indirectos");
        field_beneficiario = (JRFillField)fm.get("beneficiario");
        field_numero_mujeres = (JRFillField)fm.get("numero_mujeres");
        field_periodo_de_gracia = (JRFillField)fm.get("periodo_de_gracia");
        field_plazo = (JRFillField)fm.get("plazo");
        field_monto_liquidado = (JRFillField)fm.get("monto_liquidado");
        field_municipio = (JRFillField)fm.get("municipio");
        field_actividad_economica = (JRFillField)fm.get("actividad_economica");
        field_estado = (JRFillField)fm.get("estado");
        field_numero_acta_de_aprobacion = (JRFillField)fm.get("numero_acta_de_aprobacion");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_v_sum_total_monto_liquidado_by_report = (JRFillVariable)vm.get("v_sum_total_monto_liquidado_by_report");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)(new String("01"));
                break;
            }
            case 1 : 
            {
                value = (java.lang.String)(new String("07"));
                break;
            }
            case 2 : 
            {
                value = (java.lang.String)(new String("2007"));
                break;
            }
            case 3 : 
            {
                value = (java.lang.String)(new String("01"));
                break;
            }
            case 4 : 
            {
                value = (java.lang.String)(new String("12"));
                break;
            }
            case 5 : 
            {
                value = (java.lang.String)(new String("2007"));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 14 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_monto_liquidado.getValue()));
                break;
            }
            case 15 : 
            {
                value = (java.lang.Double)(new Double(0));
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)("logo_foncrei.jpg");
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)("Pag. " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(" / " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 19 : 
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(((java.lang.String)field_beneficiario.getValue()));
                break;
            }
            case 21 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_monto_liquidado.getValue()));
                break;
            }
            case 22 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_numero_mujeres.getValue()));
                break;
            }
            case 23 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_numero_hombres.getValue()));
                break;
            }
            case 24 : 
            {
                value = (java.lang.String)(((java.lang.String)field_rif.getValue()));
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)(((java.lang.String)field_tipo_de_organizacion.getValue()));
                break;
            }
            case 26 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_plazo.getValue()));
                break;
            }
            case 27 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_tasa.getValue()));
                break;
            }
            case 28 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_periodo_de_gracia.getValue()));
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)field_estado.getValue()));
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)field_municipio.getValue()));
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)field_sector_economico.getValue()));
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)(((java.lang.String)field_actividad_economica.getValue()));
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)(((java.lang.String)field_destino_del_credito.getValue()));
                break;
            }
            case 34 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_empleos_directos.getValue()));
                break;
            }
            case 35 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_empleos_indirectos.getValue()));
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(((java.lang.String)field_numero_acta_de_aprobacion.getValue()));
                break;
            }
            case 37 : 
            {
                value = (java.util.Date)(((java.sql.Date)field_fecha_desembolso.getValue()));
                break;
            }
            case 38 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_v_sum_total_monto_liquidado_by_report.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)(new String("01"));
                break;
            }
            case 1 : 
            {
                value = (java.lang.String)(new String("07"));
                break;
            }
            case 2 : 
            {
                value = (java.lang.String)(new String("2007"));
                break;
            }
            case 3 : 
            {
                value = (java.lang.String)(new String("01"));
                break;
            }
            case 4 : 
            {
                value = (java.lang.String)(new String("12"));
                break;
            }
            case 5 : 
            {
                value = (java.lang.String)(new String("2007"));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 14 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_monto_liquidado.getOldValue()));
                break;
            }
            case 15 : 
            {
                value = (java.lang.Double)(new Double(0));
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)("logo_foncrei.jpg");
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)("Pag. " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(" / " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 19 : 
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(((java.lang.String)field_beneficiario.getOldValue()));
                break;
            }
            case 21 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_monto_liquidado.getOldValue()));
                break;
            }
            case 22 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_numero_mujeres.getOldValue()));
                break;
            }
            case 23 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_numero_hombres.getOldValue()));
                break;
            }
            case 24 : 
            {
                value = (java.lang.String)(((java.lang.String)field_rif.getOldValue()));
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)(((java.lang.String)field_tipo_de_organizacion.getOldValue()));
                break;
            }
            case 26 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_plazo.getOldValue()));
                break;
            }
            case 27 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_tasa.getOldValue()));
                break;
            }
            case 28 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_periodo_de_gracia.getOldValue()));
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)field_estado.getOldValue()));
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)field_municipio.getOldValue()));
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)field_sector_economico.getOldValue()));
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)(((java.lang.String)field_actividad_economica.getOldValue()));
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)(((java.lang.String)field_destino_del_credito.getOldValue()));
                break;
            }
            case 34 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_empleos_directos.getOldValue()));
                break;
            }
            case 35 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_empleos_indirectos.getOldValue()));
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(((java.lang.String)field_numero_acta_de_aprobacion.getOldValue()));
                break;
            }
            case 37 : 
            {
                value = (java.util.Date)(((java.sql.Date)field_fecha_desembolso.getOldValue()));
                break;
            }
            case 38 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_v_sum_total_monto_liquidado_by_report.getOldValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)(new String("01"));
                break;
            }
            case 1 : 
            {
                value = (java.lang.String)(new String("07"));
                break;
            }
            case 2 : 
            {
                value = (java.lang.String)(new String("2007"));
                break;
            }
            case 3 : 
            {
                value = (java.lang.String)(new String("01"));
                break;
            }
            case 4 : 
            {
                value = (java.lang.String)(new String("12"));
                break;
            }
            case 5 : 
            {
                value = (java.lang.String)(new String("2007"));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 14 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_monto_liquidado.getValue()));
                break;
            }
            case 15 : 
            {
                value = (java.lang.Double)(new Double(0));
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)("logo_foncrei.jpg");
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)("Pag. " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(" / " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 19 : 
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(((java.lang.String)field_beneficiario.getValue()));
                break;
            }
            case 21 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_monto_liquidado.getValue()));
                break;
            }
            case 22 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_numero_mujeres.getValue()));
                break;
            }
            case 23 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_numero_hombres.getValue()));
                break;
            }
            case 24 : 
            {
                value = (java.lang.String)(((java.lang.String)field_rif.getValue()));
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)(((java.lang.String)field_tipo_de_organizacion.getValue()));
                break;
            }
            case 26 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_plazo.getValue()));
                break;
            }
            case 27 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_tasa.getValue()));
                break;
            }
            case 28 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_periodo_de_gracia.getValue()));
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)field_estado.getValue()));
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)field_municipio.getValue()));
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)field_sector_economico.getValue()));
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)(((java.lang.String)field_actividad_economica.getValue()));
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)(((java.lang.String)field_destino_del_credito.getValue()));
                break;
            }
            case 34 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_empleos_directos.getValue()));
                break;
            }
            case 35 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_empleos_indirectos.getValue()));
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(((java.lang.String)field_numero_acta_de_aprobacion.getValue()));
                break;
            }
            case 37 : 
            {
                value = (java.util.Date)(((java.sql.Date)field_fecha_desembolso.getValue()));
                break;
            }
            case 38 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_v_sum_total_monto_liquidado_by_report.getEstimatedValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
