/*
 * Generated by JasperReports - 4/8/07 4:15 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import java.util.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class plan_amortizacion_1176063337421_190072 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_REPORT_DATE_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_p_id_prestamo = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_SUBREPORT_DIR = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillField field_nombre_empresa = null;
    private JRFillField field_nombre_formula = null;
    private JRFillField field_tasa_vigente = null;
    private JRFillField field_numero_prestamo = null;
    private JRFillField field_numero_de_solicitud = null;
    private JRFillField field_monto_solicitado = null;
    private JRFillField field_frecuencia_pago = null;
    private JRFillField field_intermediado = null;
    private JRFillField field_nombre_partida = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_REPORT_DATE_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_DATE_FORMAT_FACTORY");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_p_id_prestamo = (JRFillParameter)pm.get("p_id_prestamo");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_SUBREPORT_DIR = (JRFillParameter)pm.get("SUBREPORT_DIR");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_nombre_empresa = (JRFillField)fm.get("nombre_empresa");
        field_nombre_formula = (JRFillField)fm.get("nombre_formula");
        field_tasa_vigente = (JRFillField)fm.get("tasa_vigente");
        field_numero_prestamo = (JRFillField)fm.get("numero_prestamo");
        field_numero_de_solicitud = (JRFillField)fm.get("numero_de_solicitud");
        field_monto_solicitado = (JRFillField)fm.get("monto_solicitado");
        field_frecuencia_pago = (JRFillField)fm.get("frecuencia_pago");
        field_intermediado = (JRFillField)fm.get("intermediado");
        field_nombre_partida = (JRFillField)fm.get("nombre_partida");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Long)(new Long(1));
                break;
            }
            case 1 : 
            {
                value = (java.lang.String)("./");
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 10 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_monto_solicitado.getValue()));
                break;
            }
            case 11 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_empresa.getValue()));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_numero_de_solicitud.getValue()));
                break;
            }
            case 13 : 
            {
                value = (java.lang.String)(((java.lang.Integer)field_frecuencia_pago.getValue()).intValue()==1 ? "Mensual" :
((java.lang.Integer)field_frecuencia_pago.getValue()).intValue()==3 ? "Trimestral" :
((java.lang.Integer)field_frecuencia_pago.getValue()).intValue()==6 ? "Semestral" :
((java.lang.Integer)field_frecuencia_pago.getValue()).intValue()==12 ? "Anual" : "");
                break;
            }
            case 14 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_partida.getValue()));
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_formula.getValue()));
                break;
            }
            case 16 : 
            {
                value = (java.lang.Object)(((java.lang.Long)parameter_p_id_prestamo.getValue()));
                break;
            }
            case 17 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "plan_amortizacion_sub_intermediario.jasper");
                break;
            }
            case 19 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_tasa_vigente.getValue()));
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)("logo_foncrei.jpg");
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)("Pag. " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(" / " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 23 : 
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 24 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_numero_prestamo.getValue()));
                break;
            }
            case 25 : 
            {
                value = (java.lang.Object)(((java.lang.Long)parameter_p_id_prestamo.getValue()));
                break;
            }
            case 26 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 27 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "plan_amortizacion_sub_amortizacion.jasper");
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Long)(new Long(1));
                break;
            }
            case 1 : 
            {
                value = (java.lang.String)("./");
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 10 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_monto_solicitado.getOldValue()));
                break;
            }
            case 11 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_empresa.getOldValue()));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_numero_de_solicitud.getOldValue()));
                break;
            }
            case 13 : 
            {
                value = (java.lang.String)(((java.lang.Integer)field_frecuencia_pago.getOldValue()).intValue()==1 ? "Mensual" :
((java.lang.Integer)field_frecuencia_pago.getOldValue()).intValue()==3 ? "Trimestral" :
((java.lang.Integer)field_frecuencia_pago.getOldValue()).intValue()==6 ? "Semestral" :
((java.lang.Integer)field_frecuencia_pago.getOldValue()).intValue()==12 ? "Anual" : "");
                break;
            }
            case 14 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_partida.getOldValue()));
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_formula.getOldValue()));
                break;
            }
            case 16 : 
            {
                value = (java.lang.Object)(((java.lang.Long)parameter_p_id_prestamo.getValue()));
                break;
            }
            case 17 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "plan_amortizacion_sub_intermediario.jasper");
                break;
            }
            case 19 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_tasa_vigente.getOldValue()));
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)("logo_foncrei.jpg");
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)("Pag. " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(" / " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 23 : 
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 24 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_numero_prestamo.getOldValue()));
                break;
            }
            case 25 : 
            {
                value = (java.lang.Object)(((java.lang.Long)parameter_p_id_prestamo.getValue()));
                break;
            }
            case 26 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 27 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "plan_amortizacion_sub_amortizacion.jasper");
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Long)(new Long(1));
                break;
            }
            case 1 : 
            {
                value = (java.lang.String)("./");
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 10 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_monto_solicitado.getValue()));
                break;
            }
            case 11 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_empresa.getValue()));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_numero_de_solicitud.getValue()));
                break;
            }
            case 13 : 
            {
                value = (java.lang.String)(((java.lang.Integer)field_frecuencia_pago.getValue()).intValue()==1 ? "Mensual" :
((java.lang.Integer)field_frecuencia_pago.getValue()).intValue()==3 ? "Trimestral" :
((java.lang.Integer)field_frecuencia_pago.getValue()).intValue()==6 ? "Semestral" :
((java.lang.Integer)field_frecuencia_pago.getValue()).intValue()==12 ? "Anual" : "");
                break;
            }
            case 14 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_partida.getValue()));
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)field_nombre_formula.getValue()));
                break;
            }
            case 16 : 
            {
                value = (java.lang.Object)(((java.lang.Long)parameter_p_id_prestamo.getValue()));
                break;
            }
            case 17 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "plan_amortizacion_sub_intermediario.jasper");
                break;
            }
            case 19 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_tasa_vigente.getValue()));
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)("logo_foncrei.jpg");
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)("Pag. " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(" / " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 23 : 
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 24 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_numero_prestamo.getValue()));
                break;
            }
            case 25 : 
            {
                value = (java.lang.Object)(((java.lang.Long)parameter_p_id_prestamo.getValue()));
                break;
            }
            case 26 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
                break;
            }
            case 27 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "plan_amortizacion_sub_amortizacion.jasper");
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
