source 'https://rubygems.org'

gem 'rails', '3.2.6'

gem 'jquery-rails', '= 3.1.0'


gem 'pg', '= 0.18'
gem 'fastercsv', '~> 1.5.5'
gem 'net-ldap', '~> 0.16.0'
#gem 'aspose-wordsjavaforruby'
#gem 'annotate', :git => 'git://github.com/jeremyolliver/annotate_models.git', :branch => 'rake_compatibility'
gem 'calendar_date_select', :git => 'https://github.com/paneq/calendar_date_select.git', :branch => 'rails3test'
#gem 'calendar_date_select', "~> 2.0.0"
gem 'acts_as_tree', "~> 1.5.0"
gem 'rak'
gem 'will_paginate', '= 3.0.5'
gem 'date_validator', '= 0.7.0'
gem 'roo'
gem 'haml', '= 4.0.5'
gem 'htmldoc', '= 0.2.3'
gem 'htmlentities', '=4.3.1'
gem 'rjb', '= 1.5.3'
gem 'number_to_words'
gem 'prawn', '= 0.12.0'
#gem 'prawn-rails'
gem 'spreadsheet', '= 0.9.7'
gem 'rb-readline', '~> 0.5.4'
gem 'whenever', '= 0.9.7', :require => false
#gem 'newrelic_rpm', '= 3.8.0.218'
#gem 'mongrel'
#gem 'passenger', '= 4.0.41'
gem 'rake', '= 10.3.1'
gem 'i18n', '= 0.6.9'
gem 'multi_json', '= 1.9.2'
#gem 'sprockets', '~> 2.2.1'
gem 'sprockets', '~> 2.1.3'
gem 'polyglot', '= 0.3.4'
gem 'tzinfo', '= 0.3.39'
gem 'afm', '= 0.2.0'
gem 'net-ssh', '= 2.8.0'
gem 'net-scp', '= 1.2.0'
gem 'mini_portile', '= 0.5.3'
gem 'nokogiri', '~> 1.7.1'
gem 'capybara', '= 2.2.1'
#gem 'bundler'
gem 'coffee-script-source', '= 1.7.0'
gem 'coffee-script', '= 2.2.0'
gem 'rubyzip', '= 1.2.1'
gem 'sass',   '= 3.3.5'
gem 'test-unit'
gem 'passenger'
gem 'puma'

group :assets do
  gem 'libv8', '= 3.3.10.4'
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  #gem 'therubyracer', '= 0.10.1', :platforms => :ruby
  gem 'execjs', '= 2.0.2'

  gem 'uglifier', '= 2.5.0'
end

gem 'render_anywhere'
gem 'prototype-rails'
gem 'prototype_legacy_helper', '0.0.0', :git => 'https://github.com/rails/prototype_legacy_helper.git'

group :tests do
 gem 'rspec'
 gem 'cucumber', '= 1.3.14'
 gem 'rspec-rails'
 gem 'cucumber-rails', '= 1.4.0'
end

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
  #gem 'debugger'
#gem 'rvm-capistrano', '~> 1.5.1'
group :development do
 gem 'capistrano', require: false
 #gem 'capistrano-rvm', require: false
 #gem 'capistrano-rails', require: false
 #gem 'capistrano-bundler', require: false
 #gem 'capistrano-passenger', require: false
 #gem 'capistrano-deploy', require: false
 #gem 'capistrano-scm-gitcopy', require: false
end
