insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (1,'Sistema','',,1,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (2,'Estructura Organizativa','',1,1,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (3,'Oficinas','',2,1,1);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (4,'Departamentos','',2,2,2);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (6,'Seguridad','',1,2,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (7,'Roles','',6,1,4);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (8,'Usuarios','',6,2,10);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (9,'Registro de Sucesos','',1,3,6);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (10,'Autorizaciones','',1,4,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (11,'Configurar Autorizaciones','',10,1,7);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (12,'Solicitar Autorizaciones','',10,2,8);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (13,'Aprobar Autorizaciones','',10,3,9);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (14,'Beneficiarios','',,2,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (15,'Beneficiarios Jurídicos','',14,1,31);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (16,'Beneficiarios Naturales','',14,2,32);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (17,'Trámites','',,3,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (18,'Registrar Trámite','',662,1,33);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (24,'Abrir Instancia de Aprobación Nacional','',666,2,39);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (34,'Consulta Desembolsos','',17,17,50);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (46,'Cartera','',,4,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (47,'Simulador de Financiamiento','',46,1,59);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (48,'Consulta de Préstamos','',46,2,60);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (49,'Pagos por Déposito','',46,3,61);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (52,'Cambio de Estatus','',46,8,64);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (53,'Contabilidad','',,5,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (54,'Cuentas Contables','',53,1,65);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (55,'Consultar Comprobantes','',53,2,66);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (56,'Reportes Contabilidad','',53,3,67);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (57,'General','',,6,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (58,'Parámetros Generales','',57,1,11);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (59,'Tablas Básicas','',57,2,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (62,'Recaudos','',703,110,13);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (64,'Instrumentos Financieros','',867,48,17);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (65,'Tipo de Gasto','',703,160,18);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (67,'Tipo de Organización','',864,50,20);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (68,'Origen de los Fondos','',703,100,21);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (72,'Entidades Financieras','',866,17,29);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (75,'Peritos','',867,34,12);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (76,'Profesiones','',864,36,26);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (77,'Programas','',57,3,28);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (78,'Tasas','',57,4,27);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (100,'Reportes','',,7,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (101,'Reportes de Balance / Listados','',100,21,508);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (103,'Reportes Plan de Pago / Tabla Amortización','',100,19,510);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (104,'Gestión','',,8,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (107,'Indicadores de Gestión','',104,1,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (109,'Cartera','',107,2,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (110,'Calidad de la Cartera','',109,1,514);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (111,'Indicadores de Recuperación','',109,2,515);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (112,'Edad de la Mora','',109,3,516);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (113,'Indices de Cartera','',109,1,517);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (511,'Nacionalidad','',864,30,621);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (513,'Causas de Renuncia','',703,20,623);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (514,'Instrumentos Financieros','',866,25,624);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (517,'Consulta de Trámites','',17,1,626);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (566,'Comité Nacional','',666,4,668);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (597,'Miembros de Comité','',703,80,698);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (600,'Comité Estadal','',666,3,701);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (602,'Documentación del Trámite','',661,6,42);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (603,'Suscripción de Contrato e Histórico','',17,19,615);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (611,'Riesgo y Provisión Sudeban','',703,130,726);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (612,'Riesgo y Provisión Institucional','',703,120,727);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (622,'Regiones','',659,3,738);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (623,'Estado-Municipio','',659,2,739);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (624,'Ejes','',659,1,740);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (627,'Tipos Semovientes','',761,300,743);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (629,'Pendientes por Disponibilidad','',665,56,745);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (630,'Tenencia de la Unidad de Producción','',864,46,746);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (631,'Tipo de Explotación','',761,160,747);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (632,'Experiencia','',864,19,748);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (633,'Formación','',864,22,749);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (639,'Tipo de Iniciativa','',761,190,754);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (642,'Reglas Contables','Mantenimiento Reglas Contables',53,4,757);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (645,'Reasignar Trámite','',668,1,759);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (646,'Asignar / Re-asignar Trámite','',649,1,36);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (649,'Evaluación Técnica','',661,2,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (659,'Divisiones Territoriales','',59,40,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (661,'Ruta Crediticia','',17,2,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (662,'Atención al Productor','',661,1,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (664,'Informe de Recomendación','',649,2,744);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (665,'Presupuesto','',661,4,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (666,'Instancias de Aprobación','',661,5,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (668,'Producción','',661,8,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (674,'Informe de Control de Visita','',668,2,775);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (679,'Gestionar Garantías','',17,3,801);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (681,'Reestructuración','',17,5,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (685,'Abrir Instancia de Aprobación Estadal','',666,1,784);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (686,'Firmas Autorizadas','',703,60,785);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (691,'Partidas Presupuestarias','',869,33,799);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (698,'País','',864,32,861);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (703,'Financiamiento','',59,50,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (704,'Sector Productivo','',703,150,867);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (706,'Unidad Medida','',703,170,869);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (707,'Casa Proveedora','',761,20,870);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (708,'Tipo Pasto','',761,290,871);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (709,'Ciclo Productivo','',703,30,872);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (711,'Tipo de Material','',761,200,874);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (712,'Tipo de Motor','',761,210,875);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (714,'Motivo de Visita','',761,60,877);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (715,'Marcas de Motor','',761,50,878);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (717,'Vocación de la Tierra','',761,330,880);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (719,'Tipo de Embarcación','',761,130,882);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (722,'Tipo de Nylon','',761,220,885);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (727,'Estructura de Costos','',703,50,890);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (728,'Condiciones Financiamiento','',703,40,891);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (729,'Editor de Contratos','',865,18,892);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (730,'Condición de Pasto','',761,30,893);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (731,'Tipo de Pasto Forraje','',761,230,894);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (732,'Vacunas','',761,320,895);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (733,'Especie de Variedad de Pasto','',761,40,896);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (734,'Sitios de Colocación','',761,80,897);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (735,'Tipo de Infraestructura','',761,180,898);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (736,'Tipo de Topografia','',761,270,899);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (737,'Tipo de Suelo','',761,260,900);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (738,'Tipo de Vialidad','',761,280,901);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (739,'Tipo de Fuente de Agua','',761,170,902);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (741,'Carga de Presupuesto PIDAN','',665,55,903);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (742,'Análisis Conclusión y Recomendaciones','',761,10,904);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (743,'Topicos para el Análisis','',761,310,905);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (744,'Cuentas en Banco','',866,15,906);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (745,'Tipo de Riego','',761,240,907);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (746,'Tipo de Drenaje','',761,120,908);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (747,'Tipo de Especies (Acuicultura)','',761,150,909);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (748,'Tipo de Sistema de Cultivo (Acuicultura)','',761,250,910);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (749,'Tipo de Cultivo (Acuicultura)','',761,110,911);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (750,'En Espera de Ciclo','',661,3,912);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (753,'Hierro Institucional','',703,70,913);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (754,'Abogados','',865,1,914);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (755,'Tipo de Arte de Pesca','',761,100,915);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (756,'Tipo de Equipo de Seguridad','',761,140,916);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (757,'Finanzas Liquidación','',661,7,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (758,'Trámites en Espera de Fideicomiso','',757,1,917);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (759,'Historico de Transacciones de Fideicomiso','',757,2,918);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (760,'Arrime','',46,10,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (761,'Producción','',59,100,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (762,'Técnico de Campo','',761,90,922);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (763,'Silo','',863,44,925);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (764,'Gaceta Oficial','',863,23,928);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (768,'Registro de Boletas','',760,1,919);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (769,'Pagos','',760,2,932);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (770,'Reporte Consolidado','',760,3,933);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (775,'Liquidación Transferencia','',757,4,938);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (776,'Liquidación en Cheque','',757,5,939);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (777,'Resumen de Instancia de Aprobacion','',666,8,940);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (778,'Recepción Archivo Banco','',757,6,941);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (779,'Registrar Cheques','',757,7,778);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (784,'Orden de Despacho','',661,11,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (785,'Operaciones de Ordenes de Despacho','',784,9,945);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (786,'Consulta Pago Casa Proveedora','',784,10,946);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (787,'Convenios','',868,14,947);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (788,'Tipo','',868,50,948);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (789,'Registro de Inventario','',868,39,949);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (790,'Consulta de Excedente','',760,4,950);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (791,'Rechazos de Liquidación','',17,20,951);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (792,'Rechazos de Excedente Abonos Arrime','',17,21,952);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (793,'Abono por Excedente (Transferencia)','',796,5,953);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (794,'Recepción de Archivo (Transferencia)','',796,6,954);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (795,'Confirmación Boleta','',760,2,955);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (796,'Finanzas Pago a Beneficiarios','',661,8,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (797,'Finanzas Pago Casa Proveedora','',661,9,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (798,'Pago Casa Proveedora por Transferencia','',797,8,956);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (799,'Pago Casa Proveedora por Cheque','',797,11,957);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (800,'Recepción Archivo Pago Casa Proveedora','',797,9,958);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (802,'Consulta Abonos de Excedente por Arrime','',17,22,960);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (803,'Abono por Excedente (Cheque)','',796,7,961);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (804,'Registrar cheque','',796,8,962);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (807,'Confirmación Arrimes Distintos','',760,2,965);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (808,'Comunidades Indígenas','',864,10,966);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (809,'Maquinaria','',661,4,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (810,'Cambiar Contraseña','',1,4,968);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (811,'Reimpresión Orden de Despacho','',784,11,969);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (814,'Consulta de Inventario','',17,2,1016);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (815,'Asignar Maquinaria','',809,1,967);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (816,'Liquidación de Maquinaria y Equipo','',809,4,1030);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (817,'Archivos Generados para el Pago a Casa Proveedora','',797,10,1031);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (818,'Proveedor Marino','',761,52,1032);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (822,'Rol en el Comité','',703,140,1036);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (823,'Tipo de Documento','',864,48,1037);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (825,'Transacciones Contables','',53,1,1039);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (826,'Almacén Maquinaria','',868,3,1040);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (827,'Empresas de Transporte','',868,16,1041);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (828,'Marca','',868,27,1042);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (829,'Modelo','',868,30,1043);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (830,'Consulta Movilización Maquinaria','',809,5,1044);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (831,'Envío de Maquinaria','',809,2,1045);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (833,'Recepción de Maquinaria','',809,3,1048);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (834,'Configuración de Reposición de Inventario','',868,12,1049);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (836,'Reportes con Parámetros','',100,3,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (840,'Proyección Recuperación Cartera','',836,3,1076);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (844,'Consulta de Facturas Confirmadas','',784,12,1086);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (845,'Listado del PIDAN','Listado del Presupuesto asignado al PIDAN',844,4,1087);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (846,'Créditos Otorgados Por Trimestre','Reporte de créditos otorgados por trimeste (Formato Excel)',844,5,1088);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (847,'Rendiciones Por Trimestre','Reporte de rendiciones por trimeste (Formato Excel)',844,6,1089);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (848,'Análisis de Ejecución','Analisis de Ejecución (Aprobado Versus Liquidado) (Formato Excel)',844,7,1090);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (849,'Actualización de Fideicomiso','',757,8,1091);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (850,'Consulta de Disponibilidad de Fideicomiso','',757,9,1092);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (851,'Causales de Anulación y/o Revocatoria','Tabla básica especial para las causales de la revocatoria total o parcial y la anulación',703,10,1093);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (856,'Plantillas de Boleta','',863,35,1098);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (857,'Idiomas','Tabla de todos los idiomas soportados por la aplicación',864,26,1099);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (858,'Recuperaciones','',46,5,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (859,'Agregar Gestión de Cobranzas','',858,1,1101);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (860,'Historico de Cobranzas','',858,2,1102);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (861,'Monedas','Monedas',703,90,1104);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (862,'Imputaciones','',868,25,1103);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (863,'Arrime','',59,10,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (864,'Beneficiario','',59,20,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (865,'Consultoría Jurídica','',59,30,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (866,'Finanzas','',59,60,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (867,'Garantías','',59,70,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (868,'Maquinarias','',59,80,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (869,'Presupuesto','',59,90,null);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (872,'Tipo Movimientos Fideicomiso','',866,51,1108);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (875,'Listado del PIDAN','Listado del Presupuesto asignado al PIDAN',836,4,1111);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (876,'Créditos Otorgados Por Trimestre','Reporte de créditos otorgados por trimeste (Formato Excel)',836,5,1112);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (877,'Rendiciones Por Trimestre','Reporte de rendiciones por trimeste (Formato Excel)',836,6,1113);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (878,'Análisis de Ejecución','Analisis de Ejecución (Aprobado Versus Liquidado) (Formato Excel)',836,7,1114);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (880,'Convertidor','',703,159,1116);
insert into menu (id,nombre,descripcion,parent_id,orden,opcion_id) values (881,'Nemónico','',703,99,1117);